Update wgpu to 0.12
lowenware/dotrix pull request #122
Opened 2021-12-28 10:12 UTC by QuantumEntangledAndy

This PR updates wgpu to version 0.12

Most changes were simple renames of the various structs and enums for example `wgpu::BackendBit::PRIMARY` is now `wgpu::Backends::PRIMARY`

Some notable changes were `frame.present()` must be called explicitly prior to being dropped in `release_frame` or else nothing is shown.

**Motivation:**

- The current version (0.9) dose not match the current [documentation for wgsl](https://www.w3.org/TR/WGSL/) particularly well this should help with this
  - Differences include things like no `[[block]]` and `<storage, read_write>` types
- I wanted to work on SBBO (`var<storage>`) to make some interesting shaders but couldn't get any of the examples of how to do this to validate on the current version of wgpu

**Follows ups**

- Should this get merged I intend to add the storage buffers so that larger data can be passed onto the shader than is supported in uniform
- Also if I get the time I'd like to add some examples on how to add shaders since

2021-12-29 08:41 UTC, Lowentwickler requested changes
First of all, thank you very much! I had WIP branch dedicated to the same issue, but it still unfinished. I have couple small requests and this can be merged.

2021-12-29 08:41 UTC, Lowentwickler commented on dotrix_core/src/renderer/backend.rs
> +        if let Some(f) = f {
[request]
Make it in one line please:
```
if let Some(frame) = self.frame.take() {
```

2021-12-29 08:41 UTC, Lowentwickler commented on dotrix_core/src/renderer/backend.rs
> +        // }
I believe this can be removed instead of commenting.

2021-12-29 08:57 UTC, Lowentwickler commented
I will merge it as is and then apply necessary changes. Thanks again!

2021-12-29 08:57 UTC, merged

2021-12-29 11:50 UTC, QuantumEntangledAndy commented
Thanks for merging. I a working on a branch which enables the Storage buffer type. Just need to decide how to handle read only storage and read write storage. For now I have made all storages read write type but I think I store the kind on init like this:

```rust
enum StorageBufferKind {
  Read,
  ReadWrite,
}

#[derive(Default)]
pub struct StorageBuffer {
    kind: StorageBufferKind,
    wgpu_buffer: Option<wgpu::Buffer>,
}

impl StorageBuffer {
    pub fn new_readonly() -> Self {
        Self {
            kind: StorageBufferKind::Read,
            wgpu_buffer: Default::default(),
        }
    }

    pub fn new_readwrite() -> Self {
        Self {
            kind: StorageBufferKind::ReadWrite,
            wgpu_buffer: Default::default(),
        }
    }
}
```

2021-12-29 11:54 UTC, Lowentwickler commented
I would only ask you to rename `Kind` to `Mode`, so it will fit the rest of the code.

2021-12-30 05:50 UTC, QuantumEntangledAndy commented
Sure I have done the rename to `Mode`. I am going to run it through some tests then make the PR